/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as authIndexImport } from './routes/(auth)/index'

// Create/Update Routes

const authIndexRoute = authIndexImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof authIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(auth)/': typeof authIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(auth)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  authIndexRoute: typeof authIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  authIndexRoute: authIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(auth)/"
      ]
    },
    "/(auth)/": {
      "filePath": "(auth)/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
